- name: testing templates
  hosts: servera.lab.example.com
  gather_facts: true
  vars:
    user_list:
      - albert
      - julie
      - muniandy
  tasks:
    - name: copy template to /tmp/config.cfg
      template:
        src: templates/config.cfg.j2
        dest: /tmp/config.cfg

    - name: get contents of file
      command: cat /tmp/config.cfg
      register: file_content

    - name: display contents
      debug:
        var: file_content.stdout_lines
