---
- name: variables playbook
  hosts: webservers
  tasks:
    - name: install a webserver
      ansible.builtin.yum:
        name: httpd
        state: latest

    - name: publish website
      ansible.builtin.copy:
        content: Welcome to {{ inventory_hostname }}
        dest: /var/www/html/index.html

    - name: start webserver
      ansible.builtin.service:
        name: httpd
        state: started

    - name: open firewall port
      ansible.posix.firewalld:
        service: http
        state: enabled
        permanent: yes

- name: test website
  hosts: clients
  tasks:
    - name: test website
      ansible.builtin.uri:
        url: http://servera/
        status_code: 200
...
